//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample_Voucher_Entry.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucherDetail
    {
        public int Detail_Id { get; set; }
        public int Voucher_Id { get; set; }
        public int Accounts_Id { get; set; }
        public Nullable<double> Dr_Amount { get; set; }
        public Nullable<double> Cr_Amount { get; set; }
    
        public virtual tblAccountsHead tblAccountsHead { get; set; }
        public virtual tblVoucherMaster tblVoucherMaster { get; set; }
    }
}
