//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample_Voucher_Entry.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucherMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVoucherMaster()
        {
            this.tblVoucherDetail = new HashSet<tblVoucherDetail>();
        }
    
        public int Voucher_Id { get; set; }
        public string Voucher_No { get; set; }
        public System.DateTime Voucher_Date { get; set; }
        public int Supplier_Id { get; set; }
    
        public virtual tblSupplier tblSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucherDetail> tblVoucherDetail { get; set; }
    }
}
