//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample_Voucher_Entry.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Voucher_EntryEntities : DbContext
    {
        public Voucher_EntryEntities()
            : base("name=Voucher_EntryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAccountsHead> tblAccountsHead { get; set; }
        public virtual DbSet<tblSupplier> tblSupplier { get; set; }
        public virtual DbSet<tblVoucherDetail> tblVoucherDetail { get; set; }
        public virtual DbSet<tblVoucherMaster> tblVoucherMaster { get; set; }
    }
}
